name: Deploy Express.js server to EC2 (Prod)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-prod-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Node.js version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          script: |
            node_version=$(node -v)
            if [[ $node_version == v18.* ]]; then
              echo "Node.js 18.x is already installed."
            else
              echo "Node.js 18.x is not installed. Installing now..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

      - name: Extract config.js from environment variable
        run: |
          echo "$CONFIG_JS_PROD" > backend/config.js

      - name: Copy Postgres Install script to Postgres EC2 (Prod)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SERVER_POSTGRES_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          source: "backend/scripts/install_postgres.sh"
          target: "/home/ubuntu/"


      - name: Install Postgres on Postgres EC2 (Prod)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_POSTGRES_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          script: |
            cd /home/ubuntu/backend/scripts
            ./install_postgres.sh ${{ secrets.POSTGRES_PASS_PROD }} --no-replace-database --no-replace-password

      - name: Copy Redis Install script to Redis EC2 (Prod)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SERVER_REDIS_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          source: "backend/scripts/install_redis.sh"
          target: "/home/ubuntu/"

      - name: Install Redis on Redis EC2 (Prod)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_REDIS_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          script: |
            cd /home/ubuntu/backend/scripts
            ./install_redis.sh ${{ secrets.REDIS_PRIVATE_IP_PROD }} ${{ secrets.REDIS_PASS_PROD }} --no-replace-password

      - name: Upload code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SERVER_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          source: "backend/"
          target: "/home/ubuntu/"

      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          script: |
            cd /home/ubuntu/backend
            npm install --production

      - name: Start/Restart with pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_PROD }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_PROD }}
          script: |
            cd /home/ubuntu/backend
            npm run prod