name: Build and Deploy to S3 Bucket (Beta)

on:
  push:
    branches:
      - main
      - write_actions

jobs:
  build-and-deploy-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update constants.js file
        run: sed -i 's|http://localhost:4000|$API_URL|g; s|http://localhost:3000|$STATIC_URL|g' frontend/src/constants.js
        env:
          API_URL: https://beta.roomadvisor.io/api
          STATIC_URL: https://beta.roomadvisor.io
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: frontend/
        run: npm install --legacy-peer-deps

      - name: Build React app
        working-directory: frontend/
        env:
          CI: false
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BETA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BETA }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --follow-symlinks --no-progress
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_BETA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BETA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BETA }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'frontend/build'      # optional: defaults to entire repository

