name: Deploy Express.js server to EC2 (Beta)

on:
  push:
    branches:
      - main
      - write_actions

jobs:
  build-and-deploy-beta-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Node.js version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_BETA }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_BETA }}
          script: |
            node_version=$(node -v)
            if [[ $node_version == v18.* ]]; then
              echo "Node.js 18.x is already installed."
            else
              echo "Node.js 18.x is not installed. Installing now..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

      - name: Upload code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SERVER_BETA }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_BETA }}
          source: "backend/"
          target: "/home/ubuntu/"

      - name: Start/Restart with pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_BETA }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_BETA }}
          script: |
            cd /home/ubuntu/backend
            npm run prod
      - name: Configure systemd service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_BETA }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_BETA }}
          script: |
            cd /etc/systemd/system
            sudo touch roomadvisor.service
            sudo bash -c 'cat > roomadvisor.service << EOF
            [Unit]
            Description=Room Advisor Express.js Server
            
            [Service]
            ExecStart=/usr/bin/npm prod
            Restart=always
            User=ubuntu
            Group=ubuntu
            Environment=NODE_ENV=production
            WorkingDirectory=/home/ubuntu/backend
            
            [Install]
            WantedBy=multi-user.target
            EOF'
      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_BETA }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_BETA }}
          script: |
            cd /home/ubuntu/backend
            npm install --production

      - name: Enable and start systemd service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVER_BETA }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_BETA }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl enable roomadvisor
            sudo systemctl start roomadvisor